# cross-compiling configs
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)

set(CMAKE_CXX_COMPILER $ENV{CC})
set(CMAKE_SYSROOT $ENV{SYSROOT})

#set(CMAKE_FIND_ROOT_PATH /media/nfs/usr/local/lib)
#set(CMAKE_SYSROOT /media/nfs/)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
